Mobile fixes
fastn-community/design-system pull request #1
Opened 2023-12-05 12:03 UTC by MeenuKumari28

Fixed mobile issue and added width and padding to icon button.

2023-12-05 12:05 UTC, amitu commented
@MeenuKumari28 delete the _Fifthtry folder please. Also resolve conflict.

2023-12-05 12:31 UTC, Arpita-Jaiswal approved these changes

2023-12-06 08:10 UTC, Arpita-Jaiswal requested changes

2023-12-06 08:10 UTC, Arpita-Jaiswal commented on index.ftd
> +background.solid: $colors.background.base
Use `blank-page` only

2023-12-06 08:10 UTC, Arpita-Jaiswal commented on typography.ftd
> +caption or body text:
```suggestion
caption text:
```
Heading components will only take values in caption

2023-12-06 08:10 UTC, Arpita-Jaiswal commented on typography.ftd
> +
Button text can never be added independent of button, so remove all such components

2023-12-06 08:10 UTC, Arpita-Jaiswal commented on typography.ftd
> +caption or body text:
```suggestion
body text:
```

Copy large will not take text in caption area.

2023-12-06 08:10 UTC, Arpita-Jaiswal commented on typography.ftd
> +-- end: source-code
Source code can be part of the code block only. It can't be an independent text component. So remove this.

2023-12-06 09:33 UTC, closed without merging

2023-12-06 09:33 UTC, MeenuKumari28 commented
Mobile view fixes were merged.